on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - src/**
      - src-server/**
      - src-client/**
      - src-test/**
      - xmake.lua
  push:
    paths:
      - .github/workflows/build.yml
      - src/**
      - src-server/**
      - src-client/**
      - src-test/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target_type:
          - server
          - client
        mode:
          - debug
          - release
        tests:
          - true
          - false
    runs-on: ubuntu-latest  # 更改为 Ubuntu 以支持 Linux 构建
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        # 可以在这里指定 xmake 版本，默认使用 master 分支

      - uses: matbour/setup-sentry-cli@v1
        with:
          token: ${{ SECRETS.SENTRY_TOKEN }}
          organization: ${{ SECRETS.SENTRY_ORG }}
          project: ${{ SECRETS.SENTRY_PROJECT }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u  # 更新 xmake 仓库

      - run: |
          xmake f -a x64 -m ${{ matrix.mode }} -p linux -v -y --target_type=${{ matrix.target_type }} --tests=${{ matrix.tests }}  # 更改为 Linux 平台构建

      - run: |
          xmake -v -y  # 执行构建

      - run: |
          sentry-cli debug-files upload --include-sources bin/LeviLamina  # 上传调试文件（如果有需要）

      - uses: actions/upload-artifact@v4
        with:
          name: levilamina-${{ matrix.target_type }}-${{ matrix.mode }}${{ matrix.tests == true && '-tests' || '' }}-linux-x64-${{ github.sha }}
          path: |
            bin/  # 上传生成的可执行文件
