on:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        mode:
          - debug
          - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: matbour/setup-sentry-cli@v1
        with:
          token: ${{ SECRETS.SENTRY_TOKEN }}
          organization: ${{ SECRETS.SENTRY_ORG }}
          project: ${{ SECRETS.SENTRY_PROJECT }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x86_64 -m ${{ matrix.mode }} -p linux -v -y --publish=y

      - run: |
          xmake -v -y

      - run: |
          sentry-cli debug-files upload --include-sources bin/LeviLamina

      - uses: actions/upload-artifact@v4
        with:
          name: levilamina-${{ matrix.mode }}-linux-x64-${{ github.sha }}
          path: |
            bin/

  update-release-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate release stuff (tooth.json, CHANGELOG.md, etc.)
        run: |
          npm i -g keep-a-changelog
          python scripts/validate_release.py --tag ${{ github.event.release.tag_name }}

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v2
        with:
          body: |-
            ${{ steps.extract-release-notes.outputs.release_notes }}

            | File | SHA256 |
            | ---- | ------ |

  upload-to-release:
    needs:
      - build
      - update-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: levilamina-${{ matrix.mode }}-linux-x64-${{ github.sha }}
          path: artifact

      - run: |
          cp CHANGELOG.md COPYING COPYING.LESSER README.md artifact/

      - run: |
          tar -czvf ../levilamina-${{ matrix.mode }}-linux-x64.tar.gz *
        working-directory: artifact

      - id: calculate-sha256
        run: |
          echo sha256=$(sha256sum levilamina-${{ matrix.mode }}-linux-x64.tar.gz | awk '{print $1}') >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v2
        with:
          append_body: true
          body: |-
            | levilamina-${{ matrix.mode }}-linux-x64.tar.gz | ${{ steps.calculate-sha256.outputs.sha256 }} |
          files: |
            levilamina-${{ matrix.mode }}-linux-x64.tar.gz
